VUEJS_DEV="https://vuejs.org/js/vue.js"
VUEJS="https://vuejs.org/js/vue.min.js"
BOOTSTRAPJS="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.min.js"
BOOTSTRAPJS_DEV="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.js"
JQUERY="https://bootswatch.com/_vendor/jquery/dist/jquery.min.js"
D3JS="https://d3js.org/d3.v4.min.js"

BOOTSTRAP_FLATLY="https://bootswatch.com/4/flatly/bootstrap.min.css"
BOOTSTRAP_UNITED="https://bootswatch.com/4/united/bootstrap.min.css"
BOOTSTRAP="https://bootswatch.com/_vendor/bootstrap/dist/css/bootstrap.min.css"
BOOTSTRAP_LUX="https://bootswatch.com/4/lux/bootstrap.min.css"
BOOTSTRAP_SANDSTONE="https://bootswatch.com/4/sandstone/bootstrap.min.css"
BOOTSTRAP_SLATE="https://bootswatch.com/4/slate/bootstrap.min.css"
BOOTSTRAP_JOURNAL="https://bootswatch.com/4/journal/bootstrap.css"

